# Cerebras AI models configuration
# These models use Cerebras' blazing fast inference API
#
# API Key Configuration:
# Uses CEREBRAS_API_KEY from .env

models:
  # Qwen 3 Coder 480B - Large coding model with massive context
  - id: "qwen-3-coder-480b"
    name: "Qwen 3 Coder 480B (Cerebras)"
    priority: "primary"  # Set as primary as requested
    cost_type: "paid"
    context_length: 131072  # 131k context as specified
    max_tokens: 8192
    temperature: 0.7
    api_settings:
      api_key_env: "CEREBRAS_API_KEY"
  
  # Additional Cerebras models for reference
  - id: "llama-4-scout-17b-16e-instruct"
    name: "Llama 4 Scout 17B (Cerebras)"
    priority: "normal"
    cost_type: "paid"
    context_length: 32768
    max_tokens: 4096
    temperature: 0.7
    api_settings:
      api_key_env: "CEREBRAS_API_KEY"