# Curated list of known good free models for Mind-Swarm
# These models have been tested and perform well for cyber tasks
# Last updated: 2025-08-04

curated_free_models: []
# Configuration settings
config:
  # Whether to use only curated models by default
  use_curated_only: true
  
  # Fallback strategy when all curated models are rate limited
  fallback_strategy: "use_any_free"  # Options: "use_any_free", "wait", "use_priced"
  
  # Maximum wait time before falling back to non-curated models (seconds)
  max_wait_before_fallback: 30