models:
- id: z-ai/glm-4.5-air:free
  name: GLM 4.5 Air (Free)
  provider: openrouter
  priority: primary
  cost_type: free
  context_length: 131072
  max_tokens: 4096
  temperature: 0.7
# - id: moonshotai/kimi-dev-72b:free
#   name: Kimi-Dev-72B (Free)
#   provider: openrouter
#   priority: primary
#   cost_type: free
#   context_length: 131072
#   max_tokens: 4096
#   temperature: 0.7
- id: qwen/qwen3-235b-a22b:free
  name: Qwen3-235B-A22B (Free)
  provider: openrouter
  priority: primary
  cost_type: free
  context_length: 131072
  max_tokens: 4096
  temperature: 0.7
- id: openai/gpt-5-nano
  name: GPT-5 Nano
  provider: openrouter
  priority: normal
  cost_type: paid
  context_length: 400000
  max_tokens: 4096
  temperature: 0.7
  _pricing:
    prompt: '0.00000005'
    completion: '0.0000004'
- id: google/gemini-2.5-flash-lite
  name: Gemini 2.5 Flash Lite
  provider: openrouter
  priority: normal
  cost_type: paid
  context_length: 400000
  max_tokens: 4096
  temperature: 0.7
  _pricing:
    prompt: '0.00000005'
    completion: '0.0000004'
- id: google/gemini-2.5-flash
  name: Gemini 2.5 Flash
  provider: openrouter
  priority: normal
  cost_type: paid
  context_length: 400000
  max_tokens: 4096
  temperature: 0.7
  _pricing:
    prompt: '0.00000005'
    completion: '0.0000004'

provider_settings:
  openrouter:
    site_url: http://mind-swarm:8000
    app_name: Mind-Swarm
