# Subspace Sync Configuration
# Controls how subspace_template syncs to runtime subspace

template_owned:
  # These are always overwritten from template
  - "grid/library/non-fiction/mind_swarm_tech/base_code/base_code_template"
  - "grid/library/non-fiction/mind_swarm_tech/base_code/io_cyber_template"
  - "grid/library/fiction"  # Fiction library for cybers to read
  - "grid/library/non-fiction"  # Non-fiction library (excluding cyber code templates above)
  - "grid/library/schemas"  # Library schemas
  - "boot_rom"
  - "initial_knowledge"

cyber_owned:
  # These are never overwritten (cyber modifications preserved)
  - "cybers/*"
  - "grid/community/questions"
  - "grid/community/announcements"
  - "grid/community/suggestions"
  - "grid/community/tasks"
  - "grid/community/school"
  - "grid/community/BULLETIN_BOARD.md"
  - "grid/community/cyber_directory.json"
  - "grid/library/knowledge/sections"

merge_required:
  # These require intelligent merging
  - "grid/community/flynns_arcade"  # Flynn's Arcade gets synced from template

ignore_patterns:
  - "*.pyc"
  - "__pycache__"
  - ".git"
  - "*.log"
  - ".tmp_*"
  - "high_scores_*.json"  # Don't sync high score files