name: OpenAPI Schema Check

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  export-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Export OpenAPI
        run: |
          python scripts/export_openapi.py --out docs/openapi.json

      - name: Verify schema is committed
        run: |
          git diff --exit-code -- docs/openapi.json
